//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibPPE
{
    using System;
    using System.Collections.Generic;
    
    public partial class enquete
    {
        public enquete()
        {
            this.commentaire__enquete = new HashSet<commentaire__enquete>();
            this.sequences = new HashSet<sequence>();
            this.themes = new HashSet<theme>();
        }
    
        public int id { get; set; }
        public string Intitule { get; set; }
        public Nullable<bool> isTermine { get; set; }
        public System.DateTime Date_Creation { get; set; }
        public Nullable<System.DateTime> Date_Fin { get; set; }
    
        public virtual ICollection<commentaire__enquete> commentaire__enquete { get; set; }
        public virtual ICollection<sequence> sequences { get; set; }
        public virtual ICollection<theme> themes { get; set; }
    }
}
