//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibPPE
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PPE4Entities : DbContext
    {
        public PPE4Entities()
            : base("name=PPE4Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Administrateur> Administrateurs { get; set; }
        public DbSet<cadeau> cadeaux { get; set; }
        public DbSet<commentaire__enquete> commentaire__enquete { get; set; }
        public DbSet<commentaire__quizz> commentaire__quizz { get; set; }
        public DbSet<commentaire__sondage> commentaire__sondage { get; set; }
        public DbSet<enquete> enquetes { get; set; }
        public DbSet<question__quizz> question__quizz { get; set; }
        public DbSet<question__sequence> question__sequence { get; set; }
        public DbSet<question__sondage> question__sondage { get; set; }
        public DbSet<quizz> quizzs { get; set; }
        public DbSet<quizz__complet> quizz__complet { get; set; }
        public DbSet<reponse__quizz> reponse__quizz { get; set; }
        public DbSet<reponse__sequence> reponse__sequence { get; set; }
        public DbSet<reponse__sondage> reponse__sondage { get; set; }
        public DbSet<sequence> sequences { get; set; }
        public DbSet<sondage> sondages { get; set; }
        public DbSet<sondage__complet> sondage__complet { get; set; }
        public DbSet<theme> themes { get; set; }
        public DbSet<utilisateur> utilisateurs { get; set; }
    }
}
