//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibPPE
{
    using System;
    using System.Collections.Generic;
    
    public partial class question__sequence
    {
        public question__sequence()
        {
            this.reponse__sequence = new HashSet<reponse__sequence>();
        }
    
        public int id { get; set; }
        public Nullable<int> sequence_id { get; set; }
        public string Intitule { get; set; }
    
        public virtual sequence sequence { get; set; }
        public virtual ICollection<reponse__sequence> reponse__sequence { get; set; }
    }
}
