//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibPPE
{
    using System;
    using System.Collections.Generic;
    
    public partial class sequence
    {
        public sequence()
        {
            this.question__sequence = new HashSet<question__sequence>();
        }
    
        public int id { get; set; }
        public string Intitule { get; set; }
        public Nullable<int> enquete_id { get; set; }
    
        public virtual enquete enquete { get; set; }
        public virtual ICollection<question__sequence> question__sequence { get; set; }
    }
}
