//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibPPE
{
    using System;
    using System.Collections.Generic;
    
    public partial class theme
    {
        public theme()
        {
            this.enquetes = new HashSet<enquete>();
            this.sondages = new HashSet<sondage>();
            this.theme1 = new HashSet<theme>();
            this.themes = new HashSet<theme>();
        }
    
        public int id { get; set; }
        public string Intutile { get; set; }
    
        public virtual ICollection<enquete> enquetes { get; set; }
        public virtual ICollection<sondage> sondages { get; set; }
        public virtual ICollection<theme> theme1 { get; set; }
        public virtual ICollection<theme> themes { get; set; }
    }
}
