//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPE
{
    using System;
    using System.Collections.Generic;
    
    public partial class fos_user
    {
        public int id { get; set; }
        public string username { get; set; }
        public string username_canonical { get; set; }
        public string email { get; set; }
        public string email_canonical { get; set; }
        public bool enabled { get; set; }
        public string salt { get; set; }
        public string password { get; set; }
        public Nullable<System.DateTime> last_login { get; set; }
        public string confirmation_token { get; set; }
        public Nullable<System.DateTime> password_requested_at { get; set; }
        public string roles { get; set; }
    }
}
