//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PPE4Entities : DbContext
    {
        public PPE4Entities()
            : base("name=PPE4Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Administrateur> Administrateurs { get; set; }
        public virtual DbSet<cadeau> cadeaux { get; set; }
        public virtual DbSet<commentaire__enquete> commentaire__enquete { get; set; }
        public virtual DbSet<commentaire__quizz> commentaire__quizz { get; set; }
        public virtual DbSet<commentaire__sondage> commentaire__sondage { get; set; }
        public virtual DbSet<enquete> enquetes { get; set; }
        public virtual DbSet<question__quizz> question__quizz { get; set; }
        public virtual DbSet<question__sequence> question__sequence { get; set; }
        public virtual DbSet<question__sondage> question__sondage { get; set; }
        public virtual DbSet<quizz> quizzs { get; set; }
        public virtual DbSet<quizz__complet> quizz__complet { get; set; }
        public virtual DbSet<reponse__quizz> reponse__quizz { get; set; }
        public virtual DbSet<reponse__sequence> reponse__sequence { get; set; }
        public virtual DbSet<reponse__sondage> reponse__sondage { get; set; }
        public virtual DbSet<sequence> sequences { get; set; }
        public virtual DbSet<sondage> sondages { get; set; }
        public virtual DbSet<sondage__complet> sondage__complet { get; set; }
        public virtual DbSet<theme> themes { get; set; }
        public virtual DbSet<utilisateur> utilisateurs { get; set; }
    }
}
